name: 👤 Self-Review Only
description: Balancing, Material, Collider, Validation, Prebaking, etc
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: "Issue Details"
      description: "Describe what’s wrong. Screenshots, logs, etc."
      placeholder: "e.g. Here’s what I see when…"
      value: |
        
        
        
        
        ---
    validations:
      required: false
  - type: markdown
    attributes:
      value: |

        ---
        DO NOTHING BELOW THIS LINE
        ---

  - type: textarea
    id: EditorReview
    attributes:
      label: Self Review (Complete After Assignment)
      description: Assignee must complete the following before elevating task
      value: |
        - [ ] Has task been reviewed for 100% Completion.
        - [ ] All files modularly committed to Main/Beta Branch, with references to this ticket

        _Close this ticket upon completion of above_

        ---
        
