name: 🕹 Gameplay Only
description: Gameplay, Animation, VFX, Timing Polish, etc
labels: ["Gameplay"]
body:

  - type: textarea
    id: description
    attributes:
      label: "Issue Details"
      description: "Describe what’s wrong. Screenshots, logs, etc."
      placeholder: "e.g. Here’s what I see when…"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
      
        ---

  - type: textarea
    id: EditorReview
    attributes:
      label: 1. Editor Review (Complete by Assignee)
      description: Complete the following before elevating
      value: |
        - [ ] Has task been reviewed for 100% Completion.
        - [ ] All files modularly committed to Main/Beta Branch, with references to this ticket

        _Set to "Needs Review" upon completion of above_

  - type: textarea
    id: GameplayReview
    attributes:
      label: 2. Gameplay Review (Complete by Jake/Weston)
      description: Complete the following before elevating
      value: |
        - [ ] Implementation Fulfills Requirements / Feels Good
        - [ ] No Graphic / Performance related issues

        _Close ticket upon completion of above_
        
