name: Gameplay Only Task
description: Such As (Gameplay, Animation, VFX, etc)
labels: []
body:

  - type: textarea
    id: description
    attributes:
      label: "Issue Details"
      description: "Describe what’s wrong. Screenshots, logs, etc."
      placeholder: "e.g. Here’s what I see when…"
    validations:
      required: false

  - type: textarea
    id: EditorReview
    attributes:
      label: 1. Editor Review (Complete by Assignee)
      description: Complete the following before elevating
      value: |
        - [ ] Has task been reviewed for 100% Completion.
        - [ ] All files modularly committed to Main/Beta Branch, with references to this ticket

  - type: textarea
    id: GameplayReview
    attributes:
      label: 2. Gameplay Review (Complete by Jake/Weston)
      description: Complete the following before elevating
      value: |
        - [ ] Implementation Fulfills Requirements / Feels Good
        - [ ] No Graphic / Performance related issues
        
