name: Editor Only Issue
description: For things that don't need to be in-game tested (UI, Collider, Prebaker, Validation, Materials, LOD, etc)
labels: ["bug"]
body:
  - type: checkboxes
    id: IssueTagging
    attributes:
    label: Required Review Type
    options:
        - label: 'In Editor Review'
        - label: 'Gameplay Review'
        - label: 'Code Review'
    is_task: false
  - type: textarea
    id: Description
    attributes:
      label: New In-Editor Issue
      description: For things that don't need to be in-game tested (UI, Collider, Prebaker, Validation, Materials, LOD, etc)
      placeholder: Describe the Issue. Include screenshots, Player/Server Logs, etc
    validations:
      required: false
