name: In-Editor Issue
description: For things that don't need to be in-game tested (UI, Collider, Prebaker, Validation, Materials, LOD, etc)
labels: ["bug"]
body:
  - type: textarea
    id: Description
    attributes:
      label: New In-Editor Issue
      description: For things that don't need to be in-game tested (UI, Collider, Prebaker, Validation, Materials, LOD, etc)
      placeholder: Describe the Issue. Include screenshots, Player/Server Logs, etc
    validations:
      required: false
