name: In-Editor Issue
description: For things that don't need to be in-game tested (UI, Collider, Prebaker, Validation, Materials, LOD, etc)
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to tell us your idea!
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Please describe what feedback you have here.
      placeholder: Please include screenshots, Player/Server Logs, etc
    validations:
      required: false
