name: Editor Only Issue
description: For things that don't need to be in-game tested (UI, Colliders, Prebaker, Validation, Materials, LOD, etc)
labels: []
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: "What type of task is this?"
      options:
        - "Bug"
        - "Task"
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: issue_tagging
    attributes:
      label: "Required Review Type"
      description: "Which type(s) of review does this need?"
      options:
        - label: "In Editor Review (UI, Collider, Prebake, Materials, etc)"
        - label: "Gameplay Review (Game Feel, Timing, Polish, etc)"
        - label: "Code Review (Networked Components, New Functionality, tec)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "New In-Editor Issue"
      description: "Describe what’s wrong. Screenshots, logs, etc."
      placeholder: "e.g. Here’s what I see when…"
    validations:
      required: false
