name: Editor Only Issue
description: For things that don't need to be in-game tested (UI, Colliders, Prebaker, Validation, Materials, LOD, etc)
labels: []
body:
- type: dropdown
  id: Issue Type
  attributes:
    label: What type of issue is this?
    options:
      - Bug
      - Task
    default: 0
  validations:
    required: true

  - type: checkboxes
    id: CriticalImportance
    attributes:
      label: "Critical Importance"
      description: "Is this Task/Bug of critical importance"
      options:
        - label: "Critical"
    validations:
      required: true

  - type: checkboxes
    id: IssueTagging
    attributes:
      label: "Required Review Type"
      description: "Which type(s) of review does this need?"
      options:
        - label: "In Editor Review"
        - label: "Gameplay Review"
        - label: "Code Review"
    validations:
      required: true

  - type: textarea
    id: Description
    attributes:
      label: "New In-Editor Issue"
      description: "Describe what’s wrong. Screenshots, logs, etc."
      placeholder: "e.g. Here’s what I see when…"
    validations:
      required: false
