name: New Task / Bug
description: For tasks that are ready to be assigned and complete
labels: []
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: "What type of task is this?"
      options:
        - "Bug"
        - "Task"
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: issue_tagging
    attributes:
      label: "Required Review Type"
      description: "Which type(s) of review does this need?"
      options:
        - label: "Requires Editor Review (UI, Collider, Prebake, Materials, etc)"
        - label: "Requires Gameplay Review (Game Feel, Timing, Polish, etc)"
        - label: "Requires Code Review (Networked Components, New Functionality, tec)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "New In-Editor Issue"
      description: "Describe what’s wrong. Screenshots, logs, etc."
      placeholder: "e.g. Here’s what I see when…"
    validations:
      required: false

  - type: textarea
    id: CompletionChecklist
    attributes:
      label: Completion Checklist
      description: Edit this after task has been assigned
      value: |
        - [ ] Editor Review Complete (if Needed)
        - [ ] Gameplaye Review Complete (if Needed)
        - [ ] Code Review Complete (if Needed)
