name: 🐞 Bug Report
description: File a bug report
title: ""
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Please paste your Discord username and ID in here in case we need to reach out for more info.
      placeholder: name#0000
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue. Also please describe what you expected to happen.
      placeholder: Your description goes here...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Did your game crash?
      options:
        - label: Yes, my game crashed.
          required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the bug.
      placeholder: |
        1. First I did this...
        2. Then this happened...
        3. Then...
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screen Recording or Screenshot
      description: Please paste a link to a screen recording or a screenshot to help visualize the issue.
      placeholder: |
        Your screenshot or screen capture here...

        We recommend using streamble.com to upload your video, but you can also do an unlisted Youtube video.
    validations:
      required: false