name: ✍️ Feedback
description: Give us feedback on the game.
labels: ["Feedback"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to give us feedback!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Please paste your Discord username and ID in here in case we need to reach out for more info.
      placeholder: name#0000
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Please describe what feedback you have here.
      placeholder: Your feedback goes here...
    validations:
      required: true
  - type: textarea
    attributes:
      label: (Optional) Screen Recording or Screenshot
      description: Please paste a link to a screen recording or a screenshot to help visualize your feedback.
      placeholder: |
        Your screenshot or screen capture here...

        We recommend using streamble.com to upload your video, but you can also do an unlisted Youtube video.
    validations:
      required: false
